apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: user-react-demo-rollout
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: user-react-demo-rollout
  template:
    metadata:
      labels:
        app: user-react-demo-rollout
    spec:
      containers:
        - name: user-react-demo
          image: vcixoe45.private-ncr.gov-ntruss.com/user-react-demo:latest
          env:
          - name: DEBUG
            value: "1"
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.io/os"
                    operator: In
                    values:
                      - linux
      imagePullSecrets:
        - name: alertnow-docker-rego-secret
  strategy:
    blueGreen:
      activeService: user-react-demo-active
      previewService: user-react-demo-preview
      autoPromotionEnabled: false