---
apiVersion: v1
kind: Service
metadata:
  name: user-react-demo-preview
  namespace: default
spec:
  type: NodePort
  selector:
    app: user-react-demo-rollout
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: user-react-demo-active
  namespace: default
spec:
  type: NodePort
  selector:
    app: user-react-demo-rollout
  ports:
    - port: 80
      targetPort: 80
