pipeline {
    agent none
    environment {
        PROFILE='gov'
        GIT_REPO_URL='https://github.com/chiwoo-samples/user-react-demo.git'
        GIT_REPO_BRANCH_NAME='main'
        DOCKER_REGISTRY_PRIVATE='vcixoe45.private-ncr.gov-ntruss.com'
        DOCKER_REGISTRY='alertnow-image-repo.ncr.gov-ntruss.com'
        IMAGE_NAME='frontend-demo'
    }
    options {
        timestamps()
    }
    stages {
        stage('Checkout-bitbucket') {
            agent { label 'finops-jenkins' }
            steps {
                deleteDir()
                sh 'ls -al'
                checkout(
                    [$class: 'GitSCM', branches: [[name: '*/' + env.GIT_REPO_BRANCH_NAME]],
                    extensions: [],
                    userRemoteConfigs: [[credentialsId: 'github-credentials', url: env.GIT_REPO_URL]]]
                )
            }
        }

        stage('Build-React') {
            agent { docker { image 'node:17' } }
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }

    }

    post {
        always {
            node('finops-jenkins') {
                dir("${env.WORKSPACE}") { deleteDir() }
                sh 'docker rmi ${DOCKER_REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER}'
                sh 'docker rmi ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest'
            }
        }
    }

}